version: '3'

services:
  qt-ubuntu:
    build: 
      context: ./ubuntu
    ports:
      - 3389:3389
    command: perl -v 
    #qmake -v
    volumes:
         - ./volumes/core_sources:/core_sources